meta_product_name: "theGreenRoom"
meta_title: "Enter theGreenRoom - Be your own agent"
meta_description: "theGreenRoom lets bands and venues organise their own bookings, no middle men required."
meta_image: "og-image.png" # should exist in `app/assets/images/`
