meta_product_name: "theGreenRoom"
meta_title: "Enter theGreenRoom - Be your own agent"
meta_description: "theGreenRoom lets bands and venues organise their own bookings, no middle men required."
meta_image: "placeholder/meta-image.PNG" # should exist in `app/assets/images/`
