meta_product_name: "theGreenRoom"
meta_title: "Be your own agent - Enter theGreenRoom"
meta_description: "theGreenRoom lets bands and venues organise their own bookings, no middle men required."
meta_image: "/logo/og-green-logo" # should exist in `app/assets/images/`
