meta_product_name: "The Green Room"
meta_title: "Be Your own agent - Enter The Green Room"
meta_description: "The Green Room lets bands and venues organise their own bookings, no middle men required."
meta_image: "logo/whitelogo.png" # should exist in `app/assets/images/`
